In [2]:
import pandas as pd 

clientes = pd.read_csv('clientes.csv')
vendas = pd.read_csv('vendas.csv')

In [3]:
clientes_vendas = pd.merge(clientes, vendas, on = 'cliente_id')
clientes_vendas[clientes_vendas.duplicated(subset = 'venda_id', keep = False)].sort_values('venda_id')

,cliente_id,nome,idade,cidade,data_cadastro,venda_id,produto,valor,quantidade,data_venda
1,2,Bruno,35.0,RJ,2023-02-15,102,Mouse,50.0,2.0,2023-10-02
7,2,Bruno,35.0,RJ,2023-02-15,102,Mouse,50.0,2.0,2023-10-02
2,2,Bruno,35.0,RJ,2023-02-15,107,Mouse,50.0,2.0,2023-10-02
8,2,Bruno,35.0,RJ,2023-02-15,107,Mouse,50.0,2.0,2023-10-02
9,7,Gabriel,NaN,BA,2023-06-30,108,Teclado,150.0,1.0,2023-10-06
10,7,Gabriel,NaN,BA,2023-06-30,108,Teclado,150.0,1.0,2023-10-06

In [4]:
clientes_vendas.drop_duplicates(subset = 'venda_id', inplace = True)
clientes_vendas.sort_values('venda_id')

,cliente_id,nome,idade,cidade,data_cadastro,venda_id,produto,valor,quantidade,data_venda
0,1,Ana,23.0,SP,2023-01-10,101,Notebook,3500.0,1.0,2023-10-01
1,2,Bruno,35.0,RJ,2023-02-15,102,Mouse,50.0,2.0,2023-10-02
3,3,Carlos,NaN,SP,2023-03-20,103,Teclado,120.0,1.0,2023-10-03
4,4,Daniela,29.0,NaN,2023-01-10,104,Monitor,NaN,1.0,2023-10-04
5,5,Eduardo,40.0,MG,NaN,105,Notebook,4000.0,NaN,2023-10-05
6,6,Fernanda,22.0,SP,2023-05-22,106,Mouse,60.0,3.0,NaN
2,2,Bruno,35.0,RJ,2023-02-15,107,Mouse,50.0,2.0,2023-10-02
9,7,Gabriel,NaN,BA,2023-06-30,108,Teclado,150.0,1.0,2023-10-06
11,8,NaN,31.0,SP,2023-07-01,109,NaN,200.0,2.0,2023-10-07

In [5]:
clientes_vendas.to_csv('clientes_vendas.csv', index = False)