In [14]:
import pandas as pd

clientes = pd.read_csv("clientes.csv")
vendas = pd.read_csv("vendas.csv")

In [19]:
clientes_vendas = pd.merge(clientes, vendas, on = "cliente_id")
clientes_vendas.head()

,cliente_id,nome,idade,cidade,data_cadastro,venda_id,produto,valor,quantidade,data_venda
0,1,Ana,23.0,SP,2023-01-10,101,Notebook,3500.0,1.0,2023-10-01
1,2,Bruno,35.0,RJ,2023-02-15,102,Mouse,50.0,2.0,2023-10-02
2,2,Bruno,35.0,RJ,2023-02-15,107,Mouse,50.0,2.0,2023-10-02
3,3,Carlos,NaN,SP,2023-03-20,103,Teclado,120.0,1.0,2023-10-03
4,4,Daniela,29.0,NaN,2023-01-10,104,Monitor,NaN,1.0,2023-10-04

In [28]:
clientes_gastos = clientes_vendas.groupby("nome")["valor"].sum().reset_index().sort_values("valor", ascending = False)
clientes_gastos.head()

      nome   valor
4  Eduardo  4000.0
0      Ana  3500.0
6  Gabriel   300.0
1    Bruno   200.0
2   Carlos   120.0